### ISSUE TITLE
Question on restraint creation in the protein peptide tutorial

### ISSUE THREAD

**Issue by proteins247** [maccallumlab/meld#105]
Hi there,

I have been following the protein-peptide tutorial. I have looked at the `setup_MELD.py` script: 

https://github.com/maccallumlab/meld/blob/0ddbd569e4cde10dd7a2f0e08f6a0649ad59f69a/docs/tutorial/protein_peptide_tutorial/setup_MELD.py#L56-L59

In the above section, a restraint is created with the arguments of `atom_1_res_index`, etc. These argument names are self-explanatory, but when I look at the MELD codebase and grep for such arguments, I don't find them:

https://github.com/maccallumlab/meld/blob/0ddbd569e4cde10dd7a2f0e08f6a0649ad59f69a/meld/system/restraints.py#L226-L269

Instead, I see kwargs for `atom1` and `atom2`. Is this because the tutorial script is out of date, and that the arguments to `DistanceRestraint` have been updated? Or is there some magic that interprets those kwargs? When I ran `setup_MELD.py`, I did not encounter any exceptions, and a Data directory was generated, but maybe it didn't generate the restraints correctly, with the arguments as written in the tutorial file? I haven't figured out how I might check this.

If my understanding of http://meldmd.org/explain/indexing.html is correct, the fix would be to specify atoms using `my_system.index.atom(resid, atom_name, expected_resname=None, chainid=None, one_based=False)`, where `my_system` is an instance of a MELD `System` right? I can use `one_based=True` if I wish to specify `resid` and `chainid` that start from 1 right?

**Comment by jlmaccal** [comment]
This is an issue of some things being out of date.

The tutorial is wrong. It should be as you described using `atom1` and `atom2` and using indexing.

That said, this only applies to the current master branch, which has not yet be released. You are likely using an older version of MELD that works as described in the tutorial. Essentially, we're in the midst of some major changes and those haven't quite been released yet. If you are comfortable with it, your best bet is to compile from source.
