### ISSUE TITLE
Compile issues, on all OSs.

### ISSUE THREAD

**Issue by colles2** [maccallumlab/meld#131]
I run into an issue compiling this software on Centos/RedHat 7 and 8, Ubuntu 18 and 20. I have tried CUDA 10.2 and 11.2 on all as well. I always get the same below error, of course version different based on OS tested on, but can not get past this issue. I tried both Miniconda and miniforge as well.

Error:

The following specifications were found to be incompatible with your system:
- feature:/linux-64::__glibc==2.17=0
 - feature:|@/linux-64::__glibc==2.17=0
 - meld -> __glibc[version='>=2.17']
 - meld -> cudatoolkit[version='>=11.2,<12'] -> __glibc[version='>=2.17,<3.0.a0']

If I try adding "cudatoolkit=X.X" to the conda install command and I get more errors.

**Comment by jlmaccal** [comment]
It looks like you are installing from conda rather than complying. Is that correct?

Can you give the command line you are using?

**Comment by colles2** [comment]
Yes I follow these instructions directly, here are the commands I run...

After installing Miniconda or miniforge...

conda config --add channels conda-forge 
conda config --set channel_priority strict
conda create -n my-meld-project python
conda activate my-meld-project
conda install meld

after the last command is when I get the error. I would try installing "Scratch" but the cluster they want to run this on will not allow that type of install, security. Thank

**Comment by jlmaccal** [comment]
We haven't ever seen this error before.

Can you try replacing `conda install meld` with `conda install openmm` to see if it's something wrong with our conda package or just a general problem with an incompatibility between conda and your system?

**Comment by colles2** [comment]
I have tried in on multiple OS's and tried the openmm this morning. That  did not work. So you are aware I tried on Redhat/Centos 7 and 8 and Ubuntu 18 and 20, which means I am missing something else. I will try a few more things in the morning along these lines and see what I can find.

**Comment by jlmaccal** [comment]
So, if installing openmm doesn't work, this is likely some kind of issue between the os and conda. As far as I can tell, the issue seems to be with the glibc version, but I don't really understand why this is happening.

Can you try running `conda update conda` and then try again? I also rebuilt the meld package, so it's worth trying again. I doubt either of these things will fix it though.

I'm finding a bunch of stuff on google related to this issue with conda-forge and cuda, but I haven't tracked down a solution yet.

**Comment by jlmaccal** [comment]
Can you also confirm that this is with a fresh install of miniconda and that there isn't a mix of stuff from the `default` and `condo-forge` channels?

**Comment by jlmaccal** [comment]
Finally, can you try this with `mamba` instead of `conda`?

**Comment by colles2** [comment]
To start, yes this is a new install every time I try new things. This is a safer option I always assume. As for openmm, that installed fine. I always update conda after I install miniconda as well.

Today this compiled without an issue. I tried multiple times and it worked every time. I have to assume whatever you did helped.

Thank You

**Comment by jlmaccal** [comment]
OK, I think it's because something in conda changed. I triggered a rebuild of our packages yesterday, so that probably fixed it.
