### ISSUE TITLE
Replica dependent restraints

### ISSUE THREAD

**Issue by alberto99** [maccallumlab/meld#21]
It would be great that restraints could be added to specific replicas and they would scale up and down the replica ladder as in normal.
All it would require is a new argument for restraints assigning them to a replica -- defaults to all replicas which is the current behavior.

Imagine that you want to drive your system to either state A or B. Traditionally we have meld restraints that choose either A or B and then see who wins out. What we could do with this new feature is choose 50% of replicas to direct to A and 50% to B; at the end you will see which of the two has been more time at the lowest replica index. 

This is a simple example, but there many possibilities that could go beyond what we can currently do with MELD.

**Comment by jlmaccal** [comment]
@alberto99 Does cb31d83e3d1745037ba22045caa480a4eb2b2a25 address this issue at all? It allows for the number of active restraints to vary with alpha. Currently there are linear and non-linear scalers for this, but we could come up with others if needed.

**Comment by jlmaccal** [comment]
@alberto99 Can you elaborate on what you want to do here? I'm not sure I totally understand.
