### ISSUE TITLE
removing GAFF command from MELD leaprc

### ISSUE THREAD

**Issue by lvotapka** [maccallumlab/meld#23]
Hey Team,

I shared one of the leaprc files generated by MELD with Carlos Simmerling, and he recommended that we remove the line that sources GAFF because of concerns about compatibility with GB and the PBradii command.

If I comment out the line to append that command to the "leap_cmds" variable in line 173 of the protein.py script, MELD still seems to run fine.

**Comment by alberto99** [comment]
Hi Lane, that's going g to break the functionality of anyone using gaff
parameters for ligands or modified amino acids.
The real thing g is to test weather or not the radii are changing.
Al.

**Comment by jlmaccal** [comment]
@alberto99 Can you look into this to see if need to change anything or if we can close?
