### ISSUE TITLE
Segmentation fault for large sequences

### ISSUE THREAD

**Issue by lvotapka** [maccallumlab/meld#24]
When starting from large sequences (>~260 residues), the tleap program will segfault. I found a solution to this problem by adding a newline into the tleap script generated by MELD in the middle of the "sequence" command. Do you guys want me to share this bugfix with you by lodging a pull request?

**Comment by jlmaccal** [comment]
A pull request is probably best.

Presumably tleap has a limit to the maximum line length.

It would be good to:

- Figure out what this is.
- Pass the entire script that meld generates through a filter that adds line breaks as appropriate.

**Comment by alberto99** [comment]
I believe the limit depends on machine. The limit was different at bw and
our local cluster.

**Comment by jlmaccal** [comment]
That seems weird… Maybe depends on the compiler or something?

**Comment by lvotapka** [comment]
The way I coded the change was to add a counter to the loop in get_sequence_from_AA1 in the parse.py script. Then every time counter reached a multiple of 200, it would add a newline string to the "output" list. That way, when the list is joined, the newline occurs often enough to prevent the segfault. I can change the number 200 to anything else. In fact, we could even do a really small number like 15 or 20 just to be safe.

**Comment by jlmaccal** [comment]
No, 200 is probably fine if that works. Go ahead and submit a PR.

**Comment by jlmaccal** [comment]
@lvotapka @alberto99: Did we ever get a fix for this?
