### ISSUE TITLE
Update force field to ff14SB

### ISSUE THREAD

**Issue by jlmaccal** [maccallumlab/meld#26]
Recent versions of Amber no longer include ff12SB, which is currently the default force field option.

@alberto99: do you think we should change the default to ff14SB?

**Comment by alberto99** [comment]
@jlmaccal We should update to ff14SBside. It uses ff99SB backbone and ff14SB side chains. I haven't seen a lot of difference between ff12SB + cmap and ff14SB side -- but the quality of side chain parameters is supposed to be much better according to S. Piana.
