### ISSUE TITLE
secondary structure restraints

### ISSUE THREAD

**Issue by alberto99** [maccallumlab/meld#27]
Hi @jlmaccal,
I was working on testing the REST2 implementation (meld v. 0.3.0) and started by trying to reproduce standard folding of proteins in implicit solvent...
My ubiquitin and proteinG runs now look like helix bundles which makes no sense at all unless some transformers were not implemented correctly when doing the REST2 implementation. 
Can you reproduce this? 
If confirmed, this is a major bug that is going to produce bad results for anyone working with this version.

**Comment by jlmaccal** [comment]
@alberto99 That's not a lot to go on. Can you provide more detail?

It's possible there is a bug, but I don't see what would cause things to turn into helix bundles.

**Comment by alberto99** [comment]
The helix bundle thing could be a force field issue. The point is that we are supposed to observe extended regions if the restraints are in use.

--------------------------------------------------
Alberto Perez (Homepage <http://alberto4web.wordpress.com/>)
Laufer Junior Fellow
Laufer Center for Physical and Quantitative Biology
Stony Brook University
Watch my TEDx talk <http://bit.ly/1h5bUTj>: You can't always blame your parents!

**Comment by jlmaccal** [comment]
Can you post your setup file?

**Comment by alberto99** [comment]
#!/usr/bin/env python
# encoding: utf-8

import numpy as np
from meld.remd import ladder, adaptor, master_runner
from meld import comm, vault
from meld import system
from meld import parse
import meld.system.montecarlo as mc
from meld.system.restraints import LinearRamp,ConstantRamp
from collections import namedtuple



N_REPLICAS = 30
N_STEPS = 50000
BLOCK_SIZE = 100


hydrophobes = 'AILMFPWV'
hydrophobes_res = ['ALA','ILE','LEU','MET','PHE','PRO','TRP','VAL']

def choose_hydrophobic_factor(ContactOrder):
    factor = 1.8834*np.log(ContactOrder) - 2.4853
    if factor < 1.:
       factor = 1.
    return factor
    
def choose_strandpair_factor(ContactOrder):
    factor = 1.6856*np.log(ContactOrder) - 3.0749
    if factor < 1.:
       factor = 1.
    return factor
    
def choose_hbond_factor(ContactOrder):
    factor = 1.6691*np.log(ContactOrder) - 1.9437
    if factor < 1.:
       factor = 1.
    return factor

class make_CO_scaler(object):
    def __init__(self,system=None,scaler_type='plateaunonlinear',alpha_min=0,alpha_one=0.25,alpha_two=0.5,alpha_max=1.0,strength_at_alpha_min=1.0, strength_at_alpha_max=0.0):
        self._system = system
	self._scaler_type = scaler_type
        self._alpha_min = alpha_min
        self._alpha_one = alpha_one
        self._alpha_two = alpha_two
        self._alpha_max = alpha_max
        self._strength_at_alpha_min = strength_at_alpha_min
        self._strength_at_alpha_max = strength_at_alpha_max


    def __call__(self,CO,type):
        if (type is 'hydrophobic'):
           factor = choose_hydrophobic_factor(CO)
        if (type is 'strand'):
           factor = choose_strandpair_factor(CO)
        if (type is 'Hbond'):
           factor = choose_hbond_factor(CO)
        if self._alpha_one:
            print type,self._alpha_min,self._alpha_max
            self._system.restraints.create_scaler(self._scaler_type, alpha_min=self._alpha_min, alpha_one=self._alpha_one, alpha_two=self._alpha_two, alpha_max=self._alpha_max, factor=factor, strength_at_alpha_min=self._strength_at_alpha_min, strength_at_alpha_max=self._strength_at_alpha_max)
        else:
            self._system.restraints.create_scaler(self._scaler_type, alpha_min=self._alpha_min, alpha_max=self._alpha_max, factor=factor, strength_at_alpha_min=self._strength_at_alpha_min, strength_at_alpha_max=self._strength_at_alpha_max)


def make_ss_groups(subset=None):
           active = 0
           extended = 0
           sse = []
           ss = open('ss.dat','r').readlines()[0]
           for i,l in enumerate(ss.rstrip()):
               print i,l
               if l not in "HE.":
                   continue
               if l not in 'E' and extended:
                   end = i
                   sse.append((start+1,end))
                   extended = 0
               if l in 'E':
                   if i+1 in subset:
                       active = active + 1
                   if extended:
                       continue
                   else:
                       start = i
                       extended = 1
           print active
           return sse,active


def _get_secondary_sequence(filename=None, contents=None, file=None):
    contents = parse._handle_arguments(filename, contents, file)
    lines = contents.splitlines()
    lines = [line.strip() for line in lines if not line.startswith('#')]
    sequence = ''.join(lines)
    for ss in sequence:
        if not ss in 'HE.':
            raise RuntimeError('Unknown secondary structure type "{}"'.format(aa))
    return sequence



def generate_strand_pairs(s,sse,active,scaler,active_per_cent=0.85,subset=np.array([]),CO=True):
    n_res = s.residue_numbers[-1]
    subset = subset if subset.size else np.array(range(n_res))+1 
    strand_pair = []
    for i in range(len(sse)):
        start_i,end_i = sse[i]
        for j in range(i+1,len(sse)):
            start_j,end_j = sse[j]
            
            for res_i in range(start_i,end_i+1):
                for res_j in range(start_j,end_j+1):
                    if res_i in subset or res_j in subset:
                        print res_i,res_j
                        g = []
                        make_pairNO(g,s,res_i,res_j,scaler,CO)
                        strand_pair.append(s.restraints.create_restraint_group(g,1))
                        g = []
                        make_pairON(g,s,res_i,res_j,scaler,CO)
                        strand_pair.append(s.restraints.create_restraint_group(g,1))
    all_rest = len(strand_pair)
    active = int(active * active_per_cent)
    print "strand_pairs:", all_rest,active
    s.restraints.add_selectively_active_collection(strand_pair, active)

def make_pairNO(g,s,i,j,scaler,CO=True):
    contact_order = abs(i-j)
    if CO:
        tmp_scaler = scaler(contact_order,'strand')
    else:
        tmp_scaler = scaler
    g.append(s.restraints.create_restraint('distance', tmp_scaler, LinearRamp(0,100,0,1),r1=0.0, r2=0.0, r3=0.40, r4=0.55, k=250.0,
            atom_1_res_index=i, atom_1_name='N', atom_2_res_index=j, atom_2_name='O'))

def make_pairON(g,s,i,j,scaler,CO=True):
    contact_order = abs(i-j)
    if CO:
        tmp_scaler = scaler(contact_order,'strand')
    else:
        tmp_scaler = scaler
    g.append(s.restraints.create_restraint('distance', scaler,LinearRamp(0,100,0,1), r1=0.0, r2=0.0, r3=0.40, r4=0.55, k=250.0,
            atom_1_res_index=i, atom_1_name='O', atom_2_res_index=j, atom_2_name='N'))

def create_hydrophobes(s,ContactsPerHydroph=1.3,scaler=None,group_1=np.array([]),group_2=np.array([]),CO=True):
    atoms = {"ALA":['CA','CB'],
             "VAL":['CA','CB','CG1','CG2'],
             "LEU":['CA','CB','CG','CD1','CD2'],
             "ILE":['CA','CB','CG1','CG2','CD1'],
             "PHE":['CA','CB','CG','CD1','CE1','CZ','CE2','CD2'],
             "TRP":['CA','CB','CG','CD1','NE1','CE2','CZ2','CH2','CZ3','CE3','CD2'],
             "MET":['CA','CB','CG','SD','CE'],
             "PRO":['CD','CG','CB','CA']}
    #Groups should be 1 centered
    n_res = s.residue_numbers[-1]
    group_1 = group_1 if group_1.size else np.array(range(n_res))+1
    group_2 = group_2 if group_2.size else np.array(range(n_res))+1
    scaler = scaler if scaler else s.restraints.create_scaler('nonlinear', alpha_min=0.4, alpha_max=1.0, factor=4.0)

    #Get a list of names and residue numbers, if just use names might skip some residues that are two
    #times in a row
    #make list 1 centered
    sequence = [(i,j) for i,j in zip(s.residue_numbers,s.residue_names)]
    sequence = sorted(set(sequence))
    sequence = dict(sequence)

    print sequence
    print hydrophobes_res
    #Get list of groups with only residues that are hydrophobs
    group_1 = [ res for res in group_1 if (sequence[res] in hydrophobes_res) ]
    group_2 = [ res for res in group_2 if (sequence[res] in hydrophobes_res) ]


    pairs = []
    hydroph_restraints = []
    for i in group_1:
        for j in group_2:

            # don't put the same pair in more than once
            if ( (i,j) in pairs ) or ( (j,i) in pairs ):
                continue

            if ( i ==j ):
                continue

            if (abs(i-j)< 7):
                continue
            pairs.append( (i,j) )
           
            atoms_i = atoms[sequence[i]]
            atoms_j = atoms[sequence[j]]
   
            local_contact = []
            for a_i in atoms_i:
                for a_j in atoms_j:
                    if CO:
                        print i,j,a_i,a_j
                        tmp_scaler = scaler(abs(i-j), 'hydrophobic')
                    else:
                        tmp_scaler = scaler
                    local_contact.append(s.restraints.create_restraint('distance', tmp_scaler, LinearRamp(0,100,0,1),r1=0.0, r2=0.0, r3=0.50, r4=0.70, k=250.0,
            atom_1_res_index=i, atom_1_name=a_i, atom_2_res_index=j, atom_2_name=a_j))

            hydroph_restraints.append(s.restraints.create_restraint_group(local_contact,1))
            print 'hydroph:',i,j
    all_rest = len(hydroph_restraints)
    active = int( ContactsPerHydroph * len(group_1) )
    print active,len(group_1),all_rest
    s.restraints.add_selectively_active_collection(hydroph_restraints, active)


def create_HydrogenBond(s,HBPerResidue=0.10,scaler=None,group_1=np.array([]),group_2=np.array([]),CO=True):
    all_donor = ['N']
    all_acceptor = ['O']
    acceptors = {"SER":['OG'],
             "THR":['OG1'],
             "CYS":['SG'],
             "TYR":['OH'],
             "ASN":['OD1','ND2'],
             "GLN":['OE1','NE2'],
             "ASP":['OD1','OD2'],
             "GLU":['OE1','OE2'],
             "ARG":['NE','NH1','NH2'],
             "HIE":['ND1','NE2']}
    donors = {"SER":['OG'],
             "THR":['OG1'],
             "CYS":['SG'],
             "TYR":['OH'],
             "ASN":['ND2'],
             "GLN":['NE2'],
             "LYS":['NZ'],
             "ARG":['NE','NH1','NH2'],
             "HIE":['NE2'],
             "LYS":['NZ']}

    #Groups should be 1 centered
    n_res = s.residue_numbers[-1]
    group_1 = group_1 if group_1.size else np.array(range(n_res))+1
    group_2 = group_2 if group_2.size else np.array(range(n_res))+1
    scaler = scaler if scaler else s.restraints.create_scaler('nonlinear', alpha_min=0.4, alpha_max=1.0, factor=4.0)

    #Get a list of names and residue numbers, if just use names might skip some residues that are two
    #times in a row
    #make list 1 centered
    sequence = [(i,j) for i,j in zip(s.residue_numbers,s.residue_names)]
    sequence = sorted(set(sequence))
    sequence = dict(sequence)

    pairs = []
    HB_restraints = []
    for i in group_1:
        for j in group_2:

            # don't put the same pair in more than once
            if ( (i,j) in pairs ) or ( (j,i) in pairs ):
                continue

            if ( i ==j ):
                continue
            #Alpha helices are 1-4, exclude them from this since they have the ss heuristic
            if (abs(i-j)< 5):
                continue
            if (abs(i-j)> 10):
                continue
            pairs.append( (i,j) )

            if CO:
                tmp_scaler = scaler(abs(i-j),'Hbond')
            else:
                tmp_scaler = scaler
           
            local_contact = []
            #i as donor
            atoms_i = [] 
	    atoms_i.extend(all_donor)
            try:  #some residues do not have donors
                atoms_i.extend(donors[sequence[i]])
            except:
                pass
            #j as acceptor
            atoms_j = [] 
	    atoms_j.extend(all_acceptor)
            try:  #some residues do not have donors
                atoms_j.extend(acceptors[sequence[j]])
            except:
                pass

            print "DONORS: ",i,sequence[i],atoms_i
            print "ACCEPTORS: ",j,sequence[j],atoms_j

            for a_i in atoms_i:
                for a_j in atoms_j:
                    local_contact.append(s.restraints.create_restraint('distance', tmp_scaler, LinearRamp(0,100,0,1),r1=0.0, r2=0.0, r3=0.50, r4=0.65, k=250.0,
            atom_1_res_index=i, atom_1_name=a_i, atom_2_res_index=j, atom_2_name=a_j))

            #j as donor
            atoms_j = [] 
	    atoms_j.extend(all_donor)
            try:  #some residues do not have donors
                atoms_i.extend(donors[sequence[j]])
            except:
                pass
            #i as acceptor
            atoms_i = [] 
	    atoms_i.extend(all_acceptor)
            try:  #some residues do not have donors
                atoms_j.extend(acceptors[sequence[j]])
            except:
                pass
            for a_i in atoms_i:
                for a_j in atoms_j:
                    local_contact.append(s.restraints.create_restraint('distance', tmp_scaler, LinearRamp(0,100,0,1),r1=0.0, r2=0.0, r3=0.50, r4=0.65, k=250.0,
            atom_1_res_index=i, atom_1_name=a_i, atom_2_res_index=j, atom_2_name=a_j))

            HB_restraints.append(s.restraints.create_restraint_group(local_contact,1))
    all_rest = len(HB_restraints)
    active = int( HBPerResidue * len(group_1) )
    print active,len(group_1),all_rest
    s.restraints.add_selectively_active_collection(HB_restraints, active)

def gen_state(s, index):
    pos = s._coordinates
    pos = pos - np.mean(pos, axis=0)
    vel = np.zeros_like(pos)
    alpha = index / (N_REPLICAS - 1.0)
    energy = 0
    return system.SystemState(pos, vel, alpha, energy,[0,0,0])


def get_dist_restraints(filename, s, scaler):
    dists = []
    rest_group = []
    lines = open(filename).read().splitlines()
    lines = [line.strip() for line in lines]
    for line in lines:
        if not line:
            dists.append(s.restraints.create_restraint_group(rest_group, 1))
            rest_group = []
        else:
            cols = line.split()
            i = int(cols[0])
            name_i = cols[1]
            j = int(cols[2])
            name_j = cols[3]
            dist = float(cols[4]) / 10.

            rest = s.restraints.create_restraint('distance', scaler,LinearRamp(0,100,0,1),
                                                 r1=0.0, r2=0.0, r3=dist, r4=dist+0.2, k=250,
                                                 atom_1_res_index=i, atom_2_res_index=j,
                                                 atom_1_name=name_i, atom_2_name=name_j)
            rest_group.append(rest)
    return dists


def setup_system():
    # load the sequence
    sequence = parse.get_sequence_from_AA1(filename='sequence.dat')
    n_res = len(sequence.split())

    # build the system
    p = system.ProteinMoleculeFromSequence(sequence)
    b = system.SystemBuilder(forcefield="ff14sbside")
    s = b.build_system_from_molecules([p])
    s.temperature_scaler = system.GeometricTemperatureScaler(0, 0.6, 300., 450.)

    #
    # Secondary Structure
    #
    ss_scaler = s.restraints.create_scaler('nonlinear', alpha_min=0.40, alpha_max=0.75, factor=4.0)
    ss_rests = parse.get_secondary_structure_restraints(filename='ss.dat', system=s,ramp=LinearRamp(0,100,0,1), scaler=ss_scaler,
            torsion_force_constant=2.5, distance_force_constant=2.5)
    n_ss_keep = int(len(ss_rests) * 0.70) #We enforce 70% of restrains 
    s.restraints.add_selectively_active_collection(ss_rests, n_ss_keep)

    #
    # Confinement Restraints
    #
    #conf_scaler = s.restraints.create_scaler('nonlinear', alpha_min=0.4, alpha_max=1.0, factor=4.0,strength_at_alpha_min=0.0, strength_at_alpha_max=1.0)
    #confinement_rests = []
    #confinement_dist = (16.9*np.log(s.residue_numbers[-1])-15.8)/28.*1.2
    #for index in range(n_res):
    #    rest = s.restraints.create_restraint('confine', conf_scaler, LinearRamp(0,100,0,1),res_index=index+1, atom_name='CA', radius=confinement_dist, force_const=250.0)
    #    confinement_rests.append(rest)
    #s.restraints.add_as_always_active_list(confinement_rests)

    #
    # Distance Restraints
    #
    # High reliability
    #
    #
    # Create Plateau kind of scalers
    #
    low_2 = make_CO_scaler(system=s,scaler_type='plateaunonlinear', alpha_min=0.70, alpha_one=0.85, alpha_two=0.85, alpha_max=1.0, strength_at_alpha_min=1.0, strength_at_alpha_max=0.0)
    low_4 = make_CO_scaler(system=s,scaler_type='plateaunonlinear', alpha_min=0.55, alpha_one=0.70, alpha_two=0.70, alpha_max=0.85, strength_at_alpha_min=1.0, strength_at_alpha_max=0.0)
    low_6 = s.restraints.create_scaler('plateaunonlinear', alpha_min=0.40, alpha_one=0.55, alpha_two=0.55, alpha_max=0.7, factor=4.0, strength_at_alpha_min=1.0, strength_at_alpha_max=0.0)
    low_8 = s.restraints.create_scaler('nonlinear', alpha_min=0.40, alpha_max=0.55, factor=4.0)
    #
    # Heuristic Restraints
    #
    subset= np.array(range(n_res)) + 1

        #
        # Hydrophobic
        #
    create_hydrophobes(s,ContactsPerHydroph=1.2/4.,scaler=low_2,group_1=subset,CO=True)
    create_hydrophobes(s,ContactsPerHydroph=1.2/2.,scaler=low_4,group_1=subset,CO=True)
    create_hydrophobes(s,ContactsPerHydroph=1.2*3/4.,scaler=low_6,group_1=subset,CO=False)
    create_hydrophobes(s,ContactsPerHydroph=1.2,scaler=low_8,group_1=subset,CO=False)

        #
        # HBonds
        #
    create_HydrogenBond(s,HBPerResidue=0.10/4.,scaler=low_2,group_1=subset,CO=True)
    create_HydrogenBond(s,HBPerResidue=0.10/2.,scaler=low_4,group_1=subset,CO=True)
    create_HydrogenBond(s,HBPerResidue=0.10*3/4.,scaler=low_6,group_1=subset,CO=False)
    create_HydrogenBond(s,HBPerResidue=0.10,scaler=low_8,group_1=subset,CO=False)

        #
        # Strand Pairing
        #
    sse,active = make_ss_groups(subset=subset)
    try:
        generate_strand_pairs(s,sse,float(active)/4.,subset=subset,scaler=low_2,CO=True)
        generate_strand_pairs(s,sse,float(active)/2.,subset=subset,scaler=low_4,CO=True)
        generate_strand_pairs(s,sse,float(active)*3/4.,subset=subset,scaler=low_6,CO=False)
        generate_strand_pairs(s,sse,float(active),subset=subset,scaler=low_8,CO=False)
    except:
        pass

    # setup mcmc at startup
    movers = []
    n_atoms = s.n_atoms
    for i in range(1, n_res + 1):
        n = s.index_of_atom(i, 'N') - 1
        ca = s.index_of_atom(i, 'CA') - 1
        c = s.index_of_atom(i, 'C') - 1

        mover = mc.DoubleTorsionMover(n, ca, list(range(ca, n_atoms)),
                                      ca, c, list(range(c, n_atoms)))

        movers.append((mover, 1))

    sched = mc.MonteCarloScheduler(movers, n_res * 60)

    # create the options
    options = system.RunOptions()
    options.implicit_solvent_model = 'gbNeck2'
    options.use_big_timestep = False
    options.use_bigger_timestep = True
    options.cutoff = 1.8

    options.use_amap = False
    options.amap_beta_bias = 1.0
    options.timesteps = 11111
    options.minimize_steps = 20000
    options.min_mc = sched

    # create a store
    store = vault.DataStore(s.n_atoms, N_REPLICAS, s.get_pdb_writer(), block_size=BLOCK_SIZE)
    store.initialize(mode='w')
    store.save_system(s)
    store.save_run_options(options)

    # create and store the remd_runner
    l = ladder.NearestNeighborLadder(n_trials=48 * 48)
    policy = adaptor.AdaptationPolicy(2.0, 50, 50)
    a = adaptor.EqualAcceptanceAdaptor(n_replicas=N_REPLICAS, adaptation_policy=policy)

    remd_runner = master_runner.MasterReplicaExchangeRunner(N_REPLICAS, max_steps=N_STEPS, ladder=l, adaptor=a)
    store.save_remd_runner(remd_runner)

    # create and store the communicator
    c = comm.MPICommunicator(s.n_atoms, N_REPLICAS)
    store.save_communicator(c)

    # create and save the initial states
    states = [gen_state(s, i) for i in range(N_REPLICAS)]
    store.save_states(states, 0)

    # save data_store
    store.save_data_store()

    return s.n_atoms


setup_system()

**Comment by jlmaccal** [comment]
And this is known to work from a previous version?

**Comment by alberto99** [comment]
yes. I have run the same protocol with MELD version 0.23.
Just removing the box information [0,0,0] as now that is not an argument.

**Comment by jlmaccal** [comment]
There was a bug where MELD restraints were not being updated on the GPU. Fixed by 2a16a86c.
