### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by lvotapka** [maccallumlab/meld#29]
I'm trying to merge and update older versions of MELD. But my old setup.py scripts don't work anymore. For instance, a new parameter "box_vector" requires an argument, and I don't know what to provide. Would it be possible to include sample setup.py scripts with this repository that work with the latest code changes?

**Comment by alberto99** [comment]
Lane, 
if you are using implicit solvent  you could just use [0,0,0]:

system.SystemState(pos, vel, alpha, energy,[0,0,0])

Al.

**Comment by lvotapka** [comment]
OK thanks Al. But I still think it would be useful to include some sample setup.py scripts...

**Comment by jlmaccal** [comment]
> OK thanks Al. But I still think it would be useful to include some sample setup.py scripts...

Feel free.

**Comment by jlmaccal** [comment]
Is anyone planning to do anything here? We're really lacking in documentation and examples.
