### ISSUE TITLE
cartesian restraint causing openmm complains " Particle coordiante is nan"

### ISSUE THREAD

**Issue by frank-stonybrook** [maccallumlab/meld#33]
Hi Justin, 

I am using meld 0.3.10 combining with openmm 7.1.1. My simulation system contain one protein one ligand and several tip3p water molecules. 

I successfully setup the system and ran simulation. However I find out that the simulation crashed at the very first step every time if I apply a cartesian restraints to protein in the system like this:
###############################################################################
def make_cartesian_collections(s, scaler, residues, delta=0.35, k=250.):
    cart = []
    #backbone = ['N','CA','C','O']
    backbone = ['CA']
    #Residues are 1 based 
    #index of atoms are 1 base
    for i in residues:
        print i
        for b in backbone:
            atom_index = s.index_of_atom(i,b) - 1
            x,y,z = s.coordinates[atom_index]/10.
            print i,b,x,y,z
            rest = s.restraints.create_restraint('cartesian',scaler, res_index=i, atom_name=b,
                x=x, y=y, z=z, delta=delta,force_const=k)
            cart.append(rest)
     return cart
#################################################################################

I double checked and make sure that all the related parameters were correct.
Therefore I doubt that whether this problem could be related with the periodic boundary condition and the way openmm save the imaged system. 

Best
Cong

**Comment by frank-stonybrook** [comment]
Just find out that there are two residue: GLU31 and ASN99 that cause the cartesian restraint fail. But Still have no cue why that happens.

**Comment by jlmaccal** [comment]
Please reopen if this is still a problem.
