### ISSUE TITLE
Allow explicit water boxes in system builder

### ISSUE THREAD

**Issue by cing** [maccallumlab/meld#46]
For convenience, it would helpful to be able to make extended peptides in explicit solvent using the `SystemBuilder` alone, rather than doing some tleap stuff outside of MELD and loading the top/mdcrd. `SystemBuilder` should be modified to include new optional parameters for solvent type and box size. https://github.com/maccallumlab/meld/blob/master/meld/system/builder.py#L32

Essentially, new lines should be added to leap_cmds before `_generate_leap_footer`, something along the lines of:

```
leap_cmds.extend(["source leaprc.water.tip3p","solvateBox mol_0 TIP3PBOX 6"])
```

where the type of solvent and distance to box edge should be adjustable parameters. Of course, there are other commands like `addIons` that could also be supported as well.

Any preference on if we should make this general, to accept any leap_cmds as argument to SystemBuilder, or just specific keywords to make explicit waterboxes and ions?

By the way, does anyone know if truncated octahedron box sizes (via `solvateOct`) are inherently supported in MELD?

**Comment by jlmaccal** [comment]
It would be good to make this general. For example, adding ions. I don't think that we should require the user to know `tleap` commands. It would be better if we told MELD how to build the system and then it called `tleap` appropriately.

One issue is that for an extended protein chain, the water box is enormous. What needs to happen is a short run using a confinement potential with vacuum or implicit, followed by solvation. This might be a problem if e.g. the head node doesn't have a GPU, but maybe we could use the CPU code for this.
