### ISSUE TITLE
Issue with  "Fix bug in handling of restraint groups"

### ISSUE THREAD

**Issue by frank-stonybrook** [maccallumlab/meld#59]
Hi Guys, 

I am wondering is there any testing case which we could valid the latest bug fix (commit: d6f5068)?

Best,
Cong

**Comment by jlmaccal** [comment]
The fix passes all of the existing test suite. I was not able to develop a new test that triggered this bug, although I did try. However, I was experiencing this bug reliably on an actually simulation and can verify that it is fixed by this commit.

**Comment by frank-stonybrook** [comment]
Thanks!
