### ISSUE TITLE
OpenMM 'LocalEnergyMinimizer_minimize' failed when running MELD simulation with restraints

### ISSUE THREAD

**Issue by frank-stonybrook** [maccallumlab/meld#60]
Hi Guys, 

I am recently experiencing **LocalEnergyMinimizer_minimize** failure when running MELD simulation with restraints. I could verify that the problem disappears when I running simulation on the same system without meld restraints. 

I searched through the OpenMM documents and find out the following description about this **LocalEnergyMinimizer** function:

> Given a Context specifying initial particle positions, it searches for a nearby set of positions that represent a local minimum of the potential energy. Distance constraints are enforced during minimization by adding a harmonic restraining force to the potential function. The strength of the restraining force is steadily increased until the minimum energy configuration satisfies all constraints to within the tolerance specified by the Context's Integrator 

If I understood correctly, the OpenMM minimizer will enforcing all MELD restraints(and other constraints) by adding harmonic restraining forces to the potential function during minimization and try to find a configuration of the system which satisfied all constraints/restraints within the tolerance. 

My question is how could I resolve the minimization failure when running MELD simulation on some systems with distance restraints. 

Best,
Cong

**Comment by cing** [comment]
Could you share a script that causes this error and Justin and I can reproduce it? I've encountered crashes on step 1 of dynamics (regardless of the ramp schedule of the MELD restraints), but that's because of bad initial conditions from tleap. I recall getting some crashes on minimization but I don't have anything handy.

**Comment by frank-stonybrook** [comment]
Hi Christopher,

Thanks for looking into this issue. Here is a [test system](https://drive.google.com/file/d/1SJoynby3JuHvZL1BP20t6P21QjkkC48d/view?usp=sharing) which you could try to reproduce the failure. 
I ran some tests with multiple replicas and got inconsistent results: 4 replicas always succeed, while 30 replicas sometime succeed sometime fail. But simulation without MELD restraint will alway succeed no matter how many replicas I am using. 

Before trying to reproduce the results, could you comment on how does OpenMM minimizer handle MELD restraints during minimization? 

Thanks
Cong

**Comment by frank-stonybrook** [comment]
This issue can be closed. The simulation failed with both CUDA compiler issue and MELD distance restraints.
