### ISSUE TITLE
conda install fails

### ISSUE THREAD

**Issue by agrossfield** [maccallumlab/meld#61]
I've added the mccallum_lab channel, which seems to have some issues: 

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/mccallum_lab/noarch/repodata.json>
Elapsed: 00:00.054067
CF-RAY: 4930a6609ae42198-EWR

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/mccallum_lab

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json

**Comment by jlmaccal** [comment]
It should be `maccallum_lab`.

**Comment by agrossfield** [comment]
You can close this issue -- it was operator error.  I thought I had already added conda as a channel, but I hadn't.  Not sure how I managed to do that, but in any event the problem wasn't your fault.

**Comment by cing** [comment]
I'm just excited that you're interested in trying MELD, Alan! I wouldn't call it the most user-friendly code to use, so be sure to look at some examples of constructing interesting H,T-replica exchange ladders like this one (https://github.com/laufercenter/MeldExamples/blob/master/Physical_Insights.py). Reach out on here if you have issues in running your first scripts, the tests and slow_tests directories are instructive as well.

**Comment by agrossfield** [comment]
Thanks!  I’m not sure if it’s appropriate for the problem I’m thinking about, but it is a sparse-restraints sampling thing so it seemed worth trying.  I heard Justin give a talk on it a couple of years ago and was impressed.

Cheers,

Alan


> On Jan 3, 2019, at 10:43 AM, Christopher Ing <notifications@github.com> wrote:
> 
> I'm just excited that you're interested in trying MELD, Alan! I wouldn't call it the most user-friendly code to use, so be sure to look at some examples of constructing interesting H,T-replica exchange ladders like this one (https://github.com/laufercenter/MeldExamples/blob/master/Physical_Insights.py <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_laufercenter_MeldExamples_blob_master_Physical-5FInsights.py&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ke67rA4gKS-vnpT8OZ_DpSpsMbNUntEscB1SOIN1ouE&s=yAKCDucOYCc4VB5B2EJaIEaHdpm7svJyH6_jEUv_Ow4&e=>). Reach out on here if you have issues in running your first scripts, the tests and slow_tests directories are instructive as well.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_maccallumlab_meld_issues_61-23issuecomment-2D451182102&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ke67rA4gKS-vnpT8OZ_DpSpsMbNUntEscB1SOIN1ouE&s=MKLN4GnUUanS2-IPTwNp1cSCJWgElfN94tcAm4Vb5rs&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM-5F-2D8mR4w-2DToTur4u9J-5FDpfV5dy1aN9Uks5u-5FiUpgaJpZM4ZnU0K&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ke67rA4gKS-vnpT8OZ_DpSpsMbNUntEscB1SOIN1ouE&s=E4alqrd0_8Um-Rndtm1TF8UW1JcVeY-YduuHQaFEk1s&e=>.
> 

________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
https://orcid.org/0000-0002-5877-2789
