### ISSUE TITLE
CPU/Reference implementation of MELD restraints

### ISSUE THREAD

**Issue by jchodera** [maccallumlab/meld#62]
cc: https://github.com/pandegroup/openmm/issues/2242

Let us know how we can help!

**Comment by cing** [comment]
Thanks @jchodera, this is a long-standing issue that's prevented some essential test coverage. I wasn't aware that there was a fallback to CPU for large forces mechanism going on.

@jlmaccal  can comment on the extent of this task, it strikes me as a big one.

**Comment by frank-stonybrook** [comment]
Hi Christopher, 

This is also related with previous problem here. As peatsman suggested, having a reference platform implemented will definitely improve the robustness. If the implementation of all types of restraint is a huge task, I would say at least add a distance restraint implement of reference platform. Since I couldn't simply achieve the same kind of minimization using Amber and that's also part of reason for my simulation crash.

**Comment by cing** [comment]
For sure! Although, I was under the impression that the TimeRamp's were supposed to address this problem... to apply a restraint gradually over a number of steps, but I don't know how that factors into minimization. I'll try to check it out.

**Comment by frank-stonybrook** [comment]
If your guys need, I would also like to help on it.

**Comment by jlmaccal** [comment]
This is almost certainly a bad geometry produced by `tleap`. This happens with certain sequences, usually involving  a clash between a proline and its preceding residue. Sometimes the minimizer is unable to resolve the clash. We added code to run a short MC run on backbone torsion angles that eliminates the clashes even in cases where the minimizer fails. When I'm back in the office on Monday I'll post a script that shows how to use it.

I don't have a lot of interest in adding a CPU version of the plugin. It's not a trivial amount of work, would be too slow for anything useful, and creates to separate versions of the code that need to be maintained. The main positive I can see is that it provides a reference implementation that's a little easier to debug that can help to validate the CUDA version.

**Comment by jlmaccal** [comment]
> To be honest, I don't think adding TimeRamp gonna help solve this minimization problem. My understanding is that TimeRamp will take control of those MELD restraint during real simulation. However, as peatsman mentioned, all MELD restraints will be enforced using some sort of harmonic constraints(I don't know the exact details.) regardless whether there is a MELD TimeRamp associated with.

That isn't even remotely true. The MELD restraints are handled during minimization in exactly the same way they are at any other time. They're just a class OpenMM queries to get forces and energies.

> Another surprising thing is that once those restraints are created during setup by restraints.create_restraint(for example). Regardless of adding them to system or not, they will somehow still being considered during minimization. I had this feeling because I could only run simulation by commenting all codes related with restraints, not just by commenting out the one which add them to system(something like s.restraints.add_selectively_active_collection).

I don't think this quite right either. I suspect what you are seeing is a reflection of the fact that the CPU minimizer is somewhat better than the CUDA one. So, sometimes the CPU minimizer will be able to resolve a clash that the CUDA minimizer cannot. However, as soon as you've added any MELD restraints to your system (of any type) then you can no longer use the CPU platform as we don't implement MELD on CPU.

**Comment by jlmaccal** [comment]
OK, then we need to dig into this some more. @frank-stonybrook Can you provide a failing test case and provide details of the exact versions you are using?

**Comment by frank-stonybrook** [comment]
Hi Justin, 

I reran all my tests and could not identify a single case which can not be resolved by switching to either CUDA runtime compiler or turning on MC minimizer or adding linear ramp. I guess I was fooled by the compiler thing at beginning. 

My last question is related to the MCMC minimizer. How does the MC minimizer able to handle the large force generated by bad contact? Is it uses the OpenMM's force and energy evaluation implemented in CPU platform?

Thanks.

**Comment by jlmaccal** [comment]
> 
> My last question is related to the MCMC minimizer. How does the MC minimizer able to handle the large force generated by bad contact? Is it uses the OpenMM's force and energy evaluation implemented in CPU platform?
> 
> 

No, it uses the GPU. MELD is not implemented for CUDA, so any system that has a MELD force in it will never use the CPU version of any of the forces.

The minimizer gets stuck because it makes local moves following the forces. Sometimes the gradient leads to a local minimum that still has a bad clash, so the as soon as you try to simulate the system blows up. In contrast, the MC minimizer makes non-local moves by attempting large backbone torsional moves. These large moves can eliminate clashes even in cases where the minimizer can’t.

**Comment by cing** [comment]
An OpenCL implementation of the meld plugin with the new codebase refactoring in OpenMM 7.5.0 beta (https://github.com/openmm/openmm/pull/2488) might be a nice step towards supporting CPU in the long run. Supposedly you can run OpenCL in CPU mode with an Intel/AMD SDK and that might enable some nice long numerical tests to run in CI.

**Comment by jlmaccal** [comment]
@cing I've been vaguely aware of the new common compute framework. It would definitely be interesting to port things over, but I don't know how involved that would be.
