### ISSUE TITLE
Remove OneDimCom plugin

### ISSUE THREAD

**Issue by jlmaccal** [maccallumlab/meld#7]
I have been doing umbrella sampling using MELD. Currently, this is done using a plugin to implement the necessary forces. OpenMM now supports a `CustomCentroidBondForce` that will allow us to retire the plugin.

**Comment by alberto99** [comment]
I thought this was used somewhere else, I usually get some messages when I don't compile it when running meld.

**Comment by jlmaccal** [comment]
No, it's only used for one type of restraint in MELD, which I added for doing umbrella sampling. It will complain every time you `import meld` if you don't have the plugin installed. There won't be any need for the plugin in the future as this can be implemented using custom forces.
