### ISSUE TITLE
OpenMMSwigHeaders.i: Syntax Error

### ISSUE THREAD

**Issue by ca-taylor** [maccallumlab/meld#76]
When attempting to build "meld" I encounter the following error during the final "make PythonInstall" step.

[100%] Generating MeldPluginWrapper.cpp
cd /home/chasman/meld/plugin/build/python && /bin/swig -python -c++ -o MeldPluginWrapper.cpp -I/apps/cuda/10.0.130/intel/2018.1.163/openmpi/4.0.3/openmm/7.5/include /home/chasman/meld/plugin/python/meldplugin.i
/apps/cuda/10.0.130/intel/2018.1.163/openmpi/4.0.3/openmm/7.5/include/swig/OpenMMSwigHeaders.i:513: Warning 314: 'None' is a python keyword, renaming to '_None'
/apps/cuda/10.0.130/intel/2018.1.163/openmpi/4.0.3/openmm/7.5/include/swig/OpenMMSwigHeaders.i:1013: Error: Syntax error in input(3).
make[3]: *** [python/MeldPluginWrapper.cpp] Error 1
make[3]: Leaving directory `/home/chasman/meld/plugin/build'
make[2]: *** [python/CMakeFiles/PythonInstall.dir/all] Error 2
make[2]: Leaving directory `/home/chasman/meld/plugin/build'
make[1]: *** [python/CMakeFiles/PythonInstall.dir/rule] Error 2
make[1]: Leaving directory `/home/chasman/meld/plugin/build'
make: *** [python/CMakeFiles/PythonInstall.dir/rule] Error 2
--------------------------------------------------------------------------------------------------------------------

Since "OpenMMSwigHeaders.i" is generated at OpenCC build time, this seems like a bug and I'm not quite sure how to get past it.

I am using cuda/10 intel/2018 openmpi/4.0.3 python/3.8 and swig/3.0.8.   Any suggestions on how to get past this error in parsing the generated input file would be greatly appreciated and would help us help Alberto move forward on the HiPerGator cluster.

**Comment by ca-taylor** [comment]
I build OpenMM like so...

ml cuda/10.0.130  
ml intel/2018.1.163
ml openmpi/4.0.3
ml python-core/3.8   
ml swig/3.0.8   
ml doxygen/1.8.3.1   
ml cmake/3.15.6

cmake ../ \
-DCMAKE_C_FLAGS="-std=c++11" \
-DCMAKE_CXX_FLAGS="-std=c++11" \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DOPENMM_BUILD_CUDA_LIB=ON \
-DOPENMM_BUILD_OPENCL_LIB=OFF \
-DCUDA_CUDA_LIBRARY=${HPC_CUDA_LIB}/stubs/libcuda.so \
-DCMAKE_INSTALL_PREFIX=/apps/cuda/10.0.130/intel/2018.1.163/openmpi/4.0.3/openmm/7.4.2 \
-DPYTHON_EXECUTABLE=${HPC_PYTHON_BIN}/python3

**Comment by ca-taylor** [comment]
During the OpenMM build, I see this many warnings from the use of the OpenMMSwigHeaders.i file such as the following.

[ 98%] Creating OpenMM Python module sources with swig...
cd /home/chasman/OpenMM/7.4.2/build/python/src/swig_doxygen && /apps/lib/swig/3.0.8/bin/swig -python -c++ -outdir /home/chasman/OpenMM/7.4.2/build/python/simtk/openmm -o OpenMMSwig.cxx OpenMM.i
OpenMMSwigHeaders.i:483: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:527: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:597: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:620: Warning 453: Can't apply (Vec3 &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:621: Warning 453: Can't apply (Vec3 &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:622: Warning 453: Can't apply (Vec3 &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:667: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:698: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:748: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:766: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:822: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:838: Warning 453: Can't apply (OpenMM::SerializationNode &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:868: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:918: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:978: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:1005: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:1066: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:1206: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
OpenMMSwigHeaders.i:1255: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.

**Comment by ca-taylor** [comment]
Attached is the log from my OpenMM "make".  There are many warnings associated with "OpenMMSwigHeaders.i".

[make.log](https://github.com/maccallumlab/meld/files/5311490/make.log)

**Comment by frank-stonybrook** [comment]
@ca-taylor your version of swig is a bit old. Did you try the latest version?

**Comment by ca-taylor** [comment]
Is swig/3.0.12 late enough or do you recommend/suggest going to 4.0.x?

**Comment by frank-stonybrook** [comment]
I am not sure which version of swig might compatible with python 3.8. I would suggest try both. On my machine, I have MELD compiled with swig/3.0.12 and Python 3.7.6

**Comment by ca-taylor** [comment]
I will try swig/3.0.12 first.  

However, I want to emphasize that I am not hitting a compilation issue but rather a swig parsing error while attempting to generate,

     MeldPluginWrapper.cpp

Whoops, in looking at the error again, I just noticed that the “make” command is,

  "cd /home/chasman/meld/plugin/build/python && /bin/swig -python -c++ -o MeldPluginWrapper.cpp”

So, cmake has configured the Makefile to use “/bin/make” which is, indeed, quite old (2.0.10).   I’ll have to see if I can
fix that.  

Thank you for the feedback.

**Comment by ca-taylor** [comment]
Turns out that without setting,

   -DSWIG_EXECUTABLE

on the cmake command line, cmake was using the system-provided "swig" in /bin/swig which was definitely too old.  Again an undocumented feature but I was able to dig into the cmake module code and find the references to that variable. 

One last hurdle - think...

I can now build everything successfully but the final,

      make PythonInstall

ends with a not unexpected...

   copying build/lib.linux-x86_64-3.8/meldplugin.py -> /apps/python-core/3.8/lib/python3.8/site-packages
error: could not create '/apps/python-core/3.8/lib/python3.8/site-packages/meldplugin.py': Permission denied

Normally, this is solved by doing something like

     Python setup.py install --user


There must be some environment or cmake variable that will force the install to use my *local* site-packages directory.  

Do you know what that is?

**Comment by frank-stonybrook** [comment]
@ca-taylor I had a quick question for the python module installation path. I assume that you are compiling MELD on behalf of cluster users. So if you install it on your local site-package directory, wouldn't it unavailable to other users?

**Comment by ca-taylor** [comment]
Yes.  Right now, I’m in learning mode and am installing the python stuff in my local site-package directory.   Once I have something that I *know* works, I will make it available site-wide.  

Note that OpenMM and the stuff that the MELD build/install puts in the OpenMM installation tree is already globally available.  I’ll just have to stash the python modules/eggs where users can access them.  

As always, thanks for the replies and feedback.

**Comment by frank-stonybrook** [comment]
I see. You are welcome, Glad it works!

**Comment by ca-taylor** [comment]
Well, I said it *builds*.  I didn’t say it works.   That will probably be the next battle.  ;)

However, all but one of the OpenMM tests pass and mpi4py seems to be working well.
As long as “MELD” does its thing, we should be in good shape.
