### ISSUE TITLE
Likelihood accuracy parameter is a static prior 

### ISSUE THREAD

**Issue by alberto99** [maccallumlab/meld#77]
For the MELD premises to work, this prior should be lower or equal than the accuracy of the data. Since we don't know the data in particular, we are always loosing some guiding power.  
Allowing the accuracy parameter to change might correct when our prior is too high or too low. 

Rosetta+Evcouplings uses a flat energy after a certain point, so it just shifts all the energies up by a constant amount if the data is not satisfied, but in our case that would conflict with forces being continuous.

**Comment by jlmaccal** [comment]
There are a few ways to approach this.

1. Have a flat energy at a certain point. It's easy to make this continuous. In fact, we already have it as `HyperbolicDistanceRestraint`. The problem with this approach is when the model is really bad, the energy can be completely flat with zero forces.
2. Make the accuracy a parameter. This would involve putting a prior over the accuracy and then using some type of MC to update the accuracy parameter. This is simple in concept, but implementing it could be challenging. There are also a few things that have to be decided. Is the accuracy a global parameter or a per-replica parameter? There is also the potential issue that structures that are compatible with a wide variety of accuracies will be sampled more frequently than those that are compatible with a smaller range of accuracies (kind of like the old "spring entropy" problem).
3. Compute a single maximum a priori (MAP) estimate of the accuracy using post-processing. Here, you basically guess at the accuracy as we do now. You then post-process to calculate a particular quantity (I have this in my notes somewhere) to find an estimate of the best value for accuracy. You then another round of simulation with this new accuracy, potentially repeating this cycle a few times. I worked out how to do this, but would have to find it in my notes.

I think that option 3 is probably the easiest and also possibly the best approach. If you are interested in working together on this, I should find my notes and we should set up a meeting.

**Comment by alberto99** [comment]
Thanks for your thoughts Justin,
I agree that 1 has the problem of no long range forces so for our purposes
it will not accelerate sampling.

In option 2, i would like this to be a per replica parameter, but they
would have to be coupled in some way (e.g. nudged elastic band
procedures?). Satisfying different number of restraints in different
replicas can create bottlenecks as again we have no pressure on some
degrees of freedom which suddenly will add a high energy. That might
require something like MD/MC steps to adapt? I hear you regarding the
spring entropy and this is something that i would like to avoid as well.

I'm interested to hear more about option 3. We have done a naive approach
here where we ran multiple simulations in parallel with different % of data
to trust. And we then evaluate our success based on spring energy/agreement
with original data (CryoEM in this case). But, it is not systematic and
there is room for improvement. Looks like you have a more principled way.
Let's find some time on the week of Jan 11th to catch up on this, if
possible.

**Comment by jlmaccal** [comment]
This is now implemented in the master branch. There is some documentation.
